c = ord(input("c:"))
print(c)
print(chr(c+1))

s1, s2 = input("s1 s2:").split()
print(s1[0:2] + s2[1] * 3)

n1, n2, n3 = input("n1 -n2 n3(16):").split()
print('%x'%int(n1), '%X'%int(n1))
print(-int(n2))
print('%o'%int(n3,16))

f1, f2 = input("f1:f2:").split(':')
print('\"', f1, f2, '\'', sep='\\')
print('\"', format(float(f1) + float(f2)), format((float(f1) + float(f2)) / 2, ".0f"),'\'', sep='\\')
print('\"', format(float(f1) - float(f2), ".1f"),'\'', sep='\\')
print('\"', format(float(f1) * float(f2), ".2f"),'\'', sep='\\')
print('\"', format(float(f1) // float(f2), ".3f"),'\'', sep='\\')
print('\"', format(float(f1) % float(f2),".4f"),'\'', sep='\\')
print('\"', format(float(f1) ** float(f2),".5f"),'\'', sep='\\')